stages:
    - test
    - pages

mypy:
    image: python:3.10
    stage: test
    script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install mypy
        - mypy --install-types --non-interactive
        - mypy
    after_script:
        - pip install anybadge
        - mkdir public
        - anybadge -l MyPy -v $CI_JOB_STATUS -f public/mypy.svg "success"=green "failed"=red
    artifacts:
        paths:
            - public
        when: always
    allow_failure: true
    only:
        - master

pytest:
    image: python:3.10
    stage: test
    #script:
        #- pip install --upgrade pip
        #- pip install -r requirements.txt
        #- pip install pytest
        #- python -m pytest
    #after_script:
        #- pip install anybadge
        #- mkdir public
        #- anybadge -l Pytest -v $CI_JOB_STATUS -f public/pytest.svg "success"=green "failed"=red
    #artifacts:
        #paths:
            #- public
        #when: always
    allow_failure: true
    only:
        - master

pages:
    image: python:3.10
    stage: pages
    script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install pdoc
        - pdoc -o public/ src/cocopye
    artifacts:
      paths:
        - public
    only:
        - master
