[external]
prodigal_bin = "prodigal"
uproc_bin = "uproc-prot"
uproc_import_bin = "uproc-import"
uproc_orf_bin = "uproc-orf"
uproc_db = "none"
uproc_models = "none"
cocopye_db = "none"

[server]
public_url = "localhost:8000"
tmpdir = "none"
host = "127.0.0.1"
port = 8000
workers = 4
debug = false

[server.celery]
# Due to some strange problem it is currently not possible to change this options (backend and broker). Looks like you
# have to use redis. I will try to fix it in the future.
backend = "redis://localhost"
broker = "redis://localhost"
workers = 8
time_limit = 0

#####################################################################################################
# During normal use of the tool, it shouldn't be necessary to change the variables below this line. #
#####################################################################################################

[download]
prodigal_url_windows = "https://github.com/hyattpd/Prodigal/releases/download/v2.6.3/prodigal.windows.exe"
prodigal_url_linux = "https://github.com/hyattpd/Prodigal/releases/download/v2.6.3/prodigal.linux"
uproc_src = "http://uproc.gobics.de/downloads/uproc/uproc-1.2.0.tar.gz"
uproc_win = "http://uproc.gobics.de/downloads/uproc/uproc-1.2.0-win-x86_64.zip"
pfam_db24 = "http://uproc.gobics.de/downloads/db/pfam24.uprocdb.gz"
pfam_db28 = "http://uproc.gobics.de/downloads/db/pfam28.uprocdb.gz"
model = "http://uproc.gobics.de/downloads/models/model.tar.gz"
cocopye_db = "https://user.informatik.uni-goettingen.de/~n.birth/cocopye_db.zip"