# These are paths to external dependencies. They are automatically set during initialisation. You can change them to
# point to another location, for example if you have downloaded them manually.
[external]
uproc_prot_bin = "uproc-prot"
uproc_import_bin = "uproc-import"
uproc_orf_bin = "uproc-orf"
uproc_pfam_db = "none"
uproc_models = "none"
cocopye_db = "none"

# These are advanced features of CoCoPyE which are most likely not required during normal use. To avoid confusion they
# are disabled by default.
[advanced]
# Enable database subcommand. See TODO for more information.
enable_db_creator = false
# Enable web subcommand. See TODO for more information.
enable_webserver = false

[server]
public_url = "localhost:8000"
logdir = "none"
tmpdir = "none"
host = "127.0.0.1"
port = 8000
workers = 4
debug = false

[server.celery]
# Due to some strange problem it is currently not possible to change this options (backend and broker). Looks like you
# have to use redis. I will try to fix it in the future.
backend = "redis://localhost"
broker = "redis://localhost"
workers = 8
time_limit = 0